/*	Copyright: 	© Copyright 2003 Apple Computer, Inc. All rights reserved.

	Disclaimer:	IMPORTANT:  This Apple software is supplied to you by Apple Computer, Inc.
			("Apple") in consideration of your agreement to the following terms, and your
			use, installation, modification or redistribution of this Apple software
			constitutes acceptance of these terms.  If you do not agree with these terms,
			please do not use, install, modify or redistribute this Apple software.

			In consideration of your agreement to abide by the following terms, and subject
			to these terms, Apple grants you a personal, non-exclusive license, under Apple’s
			copyrights in this original Apple software (the "Apple Software"), to use,
			reproduce, modify and redistribute the Apple Software, with or without
			modifications, in source and/or binary forms; provided that if you redistribute
			the Apple Software in its entirety and without modifications, you must retain
			this notice and the following text and disclaimers in all such redistributions of
			the Apple Software.  Neither the name, trademarks, service marks or logos of
			Apple Computer, Inc. may be used to endorse or promote products derived from the
			Apple Software without specific prior written permission from Apple.  Except as
			expressly stated in this notice, no other rights or licenses, express or implied,
			are granted by Apple herein, including but not limited to any patent rights that
			may be infringed by your derivative works or by other works in which the Apple
			Software may be incorporated.

			The Apple Software is provided by Apple on an "AS IS" basis.  APPLE MAKES NO
			WARRANTIES, EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION THE IMPLIED
			WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY AND FITNESS FOR A PARTICULAR
			PURPOSE, REGARDING THE APPLE SOFTWARE OR ITS USE AND OPERATION ALONE OR IN
			COMBINATION WITH YOUR PRODUCTS.

			IN NO EVENT SHALL APPLE BE LIABLE FOR ANY SPECIAL, INDIRECT, INCIDENTAL OR
			CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
			GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
			ARISING IN ANY WAY OUT OF THE USE, REPRODUCTION, MODIFICATION AND/OR DISTRIBUTION
			OF THE APPLE SOFTWARE, HOWEVER CAUSED AND WHETHER UNDER THEORY OF CONTRACT, TORT
			(INCLUDING NEGLIGENCE), STRICT LIABILITY OR OTHERWISE, EVEN IF APPLE HAS BEEN
			ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/
// DO NOT EDIT THIS FILE - it is machine-generated by javacglue.py
#include "com_apple_audio_toolbox_MusicTrack.h"
JNIEXPORT jint JNICALL Java_com_apple_audio_toolbox_MusicTrack_MusicTrackGetSequence
  (JNIEnv *, jclass, jint inTrack, jint outSequence)
{
	return (jint)MusicTrackGetSequence((MusicTrack)inTrack, (MusicSequence *)outSequence);
}

JNIEXPORT jint JNICALL Java_com_apple_audio_toolbox_MusicTrack_MusicTrackSetDestNode
  (JNIEnv *, jclass, jint inTrack, jint inNode)
{
	return (jint)MusicTrackSetDestNode((MusicTrack)inTrack, (AUNode)inNode);
}

JNIEXPORT jint JNICALL Java_com_apple_audio_toolbox_MusicTrack_MusicTrackSetProperty
  (JNIEnv *, jclass, jint inTrack, jint inPropertyID, jint inData, jint inLength)
{
	return (jint)MusicTrackSetProperty((MusicTrack)inTrack, (UInt32)inPropertyID, (void *)inData, (UInt32)inLength);
}

JNIEXPORT jint JNICALL Java_com_apple_audio_toolbox_MusicTrack_MusicTrackGetProperty
  (JNIEnv *, jclass, jint inTrack, jint inPropertyID, jint inData, jint ioLength)
{
	return (jint)MusicTrackGetProperty((MusicTrack)inTrack, (UInt32)inPropertyID, (void *)inData, (UInt32 *)ioLength);
}

JNIEXPORT jint JNICALL Java_com_apple_audio_toolbox_MusicTrack_MusicTrackMoveEvents
  (JNIEnv *, jclass, jint inTrack, jdouble inStartTime, jdouble inEndTime, jdouble inMoveTime)
{
	return (jint)MusicTrackMoveEvents((MusicTrack)inTrack, (MusicTimeStamp)inStartTime, (MusicTimeStamp)inEndTime, (MusicTimeStamp)inMoveTime);
}

JNIEXPORT jint JNICALL Java_com_apple_audio_toolbox_MusicTrack_NewMusicTrackFrom
  (JNIEnv *, jclass, jint inSourceTrack, jdouble inSourceStartTime, jdouble inSourceEndTime, jint outNewTrack)
{
	return (jint)NewMusicTrackFrom((MusicTrack)inSourceTrack, (MusicTimeStamp)inSourceStartTime, (MusicTimeStamp)inSourceEndTime, (MusicTrack *)outNewTrack);
}

JNIEXPORT jint JNICALL Java_com_apple_audio_toolbox_MusicTrack_MusicTrackClear
  (JNIEnv *, jclass, jint inTrack, jdouble inStartTime, jdouble inEndTime)
{
	return (jint)MusicTrackClear((MusicTrack)inTrack, (MusicTimeStamp)inStartTime, (MusicTimeStamp)inEndTime);
}

JNIEXPORT jint JNICALL Java_com_apple_audio_toolbox_MusicTrack_MusicTrackCut
  (JNIEnv *, jclass, jint inTrack, jdouble inStartTime, jdouble inEndTime)
{
	return (jint)MusicTrackCut((MusicTrack)inTrack, (MusicTimeStamp)inStartTime, (MusicTimeStamp)inEndTime);
}

JNIEXPORT jint JNICALL Java_com_apple_audio_toolbox_MusicTrack_MusicTrackCopyInsert
  (JNIEnv *, jclass, jint inSourceTrack, jdouble inSourceStartTime, jdouble inSourceEndTime, jint inDestTrack, jdouble inDestInsertTime)
{
	return (jint)MusicTrackCopyInsert((MusicTrack)inSourceTrack, (MusicTimeStamp)inSourceStartTime, (MusicTimeStamp)inSourceEndTime, (MusicTrack)inDestTrack, (MusicTimeStamp)inDestInsertTime);
}

JNIEXPORT jint JNICALL Java_com_apple_audio_toolbox_MusicTrack_MusicTrackMerge
  (JNIEnv *, jclass, jint inSourceTrack, jdouble inSourceStartTime, jdouble inSourceEndTime, jint inDestTrack, jdouble inDestInsertTime)
{
	return (jint)MusicTrackMerge((MusicTrack)inSourceTrack, (MusicTimeStamp)inSourceStartTime, (MusicTimeStamp)inSourceEndTime, (MusicTrack)inDestTrack, (MusicTimeStamp)inDestInsertTime);
}

JNIEXPORT jint JNICALL Java_com_apple_audio_toolbox_MusicTrack_MusicTrackNewMIDINoteEvent
  (JNIEnv *, jclass, jint inTrack, jdouble inTimeStamp, jint inMessage)
{
	return (jint)MusicTrackNewMIDINoteEvent((MusicTrack)inTrack, (MusicTimeStamp)inTimeStamp, (const MIDINoteMessage *)inMessage);
}

JNIEXPORT jint JNICALL Java_com_apple_audio_toolbox_MusicTrack_MusicTrackNewMIDIChannelEvent
  (JNIEnv *, jclass, jint inTrack, jdouble inTimeStamp, jint inMessage)
{
	return (jint)MusicTrackNewMIDIChannelEvent((MusicTrack)inTrack, (MusicTimeStamp)inTimeStamp, (const MIDIChannelMessage *)inMessage);
}

JNIEXPORT jint JNICALL Java_com_apple_audio_toolbox_MusicTrack_MusicTrackNewMIDIRawDataEvent
  (JNIEnv *, jclass, jint inTrack, jdouble inTimeStamp, jint inRawData)
{
	return (jint)MusicTrackNewMIDIRawDataEvent((MusicTrack)inTrack, (MusicTimeStamp)inTimeStamp, (const MIDIRawData *)inRawData);
}

JNIEXPORT jint JNICALL Java_com_apple_audio_toolbox_MusicTrack_MusicTrackNewExtendedNoteEvent
  (JNIEnv *, jclass, jint inTrack, jdouble inTimeStamp, jint inInfo)
{
	return (jint)MusicTrackNewExtendedNoteEvent((MusicTrack)inTrack, (MusicTimeStamp)inTimeStamp, (const ExtendedNoteOnEvent *)inInfo);
}

JNIEXPORT jint JNICALL Java_com_apple_audio_toolbox_MusicTrack_MusicTrackNewExtendedControlEvent
  (JNIEnv *, jclass, jint inTrack, jdouble inTimeStamp, jint inInfo)
{
	return (jint)MusicTrackNewExtendedControlEvent((MusicTrack)inTrack, (MusicTimeStamp)inTimeStamp, (const ExtendedControlEvent *)inInfo);
}

JNIEXPORT jint JNICALL Java_com_apple_audio_toolbox_MusicTrack_MusicTrackNewExtendedTempoEvent
  (JNIEnv *, jclass, jint inTrack, jdouble inTimeStamp, jdouble inBPM)
{
	return (jint)MusicTrackNewExtendedTempoEvent((MusicTrack)inTrack, (MusicTimeStamp)inTimeStamp, (Float64)inBPM);
}

JNIEXPORT jint JNICALL Java_com_apple_audio_toolbox_MusicTrack_MusicTrackNewMetaEvent
  (JNIEnv *, jclass, jint inTrack, jdouble inTimeStamp, jint inMetaEvent)
{
	return (jint)MusicTrackNewMetaEvent((MusicTrack)inTrack, (MusicTimeStamp)inTimeStamp, (const MIDIMetaEvent *)inMetaEvent);
}

JNIEXPORT jint JNICALL Java_com_apple_audio_toolbox_MusicTrack_MusicTrackNewUserEvent
  (JNIEnv *, jclass, jint inTrack, jdouble inTimeStamp, jint inUserData)
{
	return (jint)MusicTrackNewUserEvent((MusicTrack)inTrack, (MusicTimeStamp)inTimeStamp, (const MusicEventUserData *)inUserData);
}

JNIEXPORT jint JNICALL Java_com_apple_audio_toolbox_MusicTrack_MusicTrackNewParameterEvent
  (JNIEnv *, jclass, jint inTrack, jdouble inTimeStamp, jint inInfo)
{
	return (jint)MusicTrackNewParameterEvent((MusicTrack)inTrack, (MusicTimeStamp)inTimeStamp, (const ParameterEvent *)inInfo);
}

JNIEXPORT jint JNICALL Java_com_apple_audio_toolbox_MusicTrack_NewMusicEventIterator
  (JNIEnv *, jclass, jint inTrack, jint outIterator)
{
	return (jint)NewMusicEventIterator((MusicTrack)inTrack, (MusicEventIterator *)outIterator);
}

JNIEXPORT jint JNICALL Java_com_apple_audio_toolbox_MusicTrack_MusicTrackSetDestMIDIEndpoint
  (JNIEnv *, jclass, jint inTrack, jint inEndpoint)
{
	return (jint)MusicTrackSetDestMIDIEndpoint((MusicTrack)inTrack, (MIDIEndpointRef)inEndpoint);
}

JNIEXPORT jint JNICALL Java_com_apple_audio_toolbox_MusicTrack_MusicTrackGetDestNode
  (JNIEnv *, jclass, jint inTrack, jint outNode)
{
	return (jint)MusicTrackGetDestNode((MusicTrack)inTrack, (AUNode *)outNode);
}

JNIEXPORT jint JNICALL Java_com_apple_audio_toolbox_MusicTrack_MusicTrackGetDestMIDIEndpoint
  (JNIEnv *, jclass, jint inTrack, jint outEndpoint)
{
	return (jint)MusicTrackGetDestMIDIEndpoint((MusicTrack)inTrack, (MIDIEndpointRef *)outEndpoint);
}

