/*	Copyright: 	© Copyright 2003 Apple Computer, Inc. All rights reserved.

	Disclaimer:	IMPORTANT:  This Apple software is supplied to you by Apple Computer, Inc.
			("Apple") in consideration of your agreement to the following terms, and your
			use, installation, modification or redistribution of this Apple software
			constitutes acceptance of these terms.  If you do not agree with these terms,
			please do not use, install, modify or redistribute this Apple software.

			In consideration of your agreement to abide by the following terms, and subject
			to these terms, Apple grants you a personal, non-exclusive license, under Apple’s
			copyrights in this original Apple software (the "Apple Software"), to use,
			reproduce, modify and redistribute the Apple Software, with or without
			modifications, in source and/or binary forms; provided that if you redistribute
			the Apple Software in its entirety and without modifications, you must retain
			this notice and the following text and disclaimers in all such redistributions of
			the Apple Software.  Neither the name, trademarks, service marks or logos of
			Apple Computer, Inc. may be used to endorse or promote products derived from the
			Apple Software without specific prior written permission from Apple.  Except as
			expressly stated in this notice, no other rights or licenses, express or implied,
			are granted by Apple herein, including but not limited to any patent rights that
			may be infringed by your derivative works or by other works in which the Apple
			Software may be incorporated.

			The Apple Software is provided by Apple on an "AS IS" basis.  APPLE MAKES NO
			WARRANTIES, EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION THE IMPLIED
			WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY AND FITNESS FOR A PARTICULAR
			PURPOSE, REGARDING THE APPLE SOFTWARE OR ITS USE AND OPERATION ALONE OR IN
			COMBINATION WITH YOUR PRODUCTS.

			IN NO EVENT SHALL APPLE BE LIABLE FOR ANY SPECIAL, INDIRECT, INCIDENTAL OR
			CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
			GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
			ARISING IN ANY WAY OUT OF THE USE, REPRODUCTION, MODIFICATION AND/OR DISTRIBUTION
			OF THE APPLE SOFTWARE, HOWEVER CAUSED AND WHETHER UNDER THEORY OF CONTRACT, TORT
			(INCLUDING NEGLIGENCE), STRICT LIABILITY OR OTHERWISE, EVEN IF APPLE HAS BEEN
			ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_apple_audio_toolbox_MusicSequence */

#ifndef _Included_com_apple_audio_toolbox_MusicSequence
#define _Included_com_apple_audio_toolbox_MusicSequence
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: firstArg4Ptr */
/* Inaccessible static: secondArg8Ptr */
/* Inaccessible static: syncObject */
/*
 * Class:     com_apple_audio_toolbox_MusicSequence
 * Method:    NewMusicSequence
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_apple_audio_toolbox_MusicSequence_NewMusicSequence
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_apple_audio_toolbox_MusicSequence
 * Method:    MusicSequenceNewTrack
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_apple_audio_toolbox_MusicSequence_MusicSequenceNewTrack
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_apple_audio_toolbox_MusicSequence
 * Method:    MusicSequenceDisposeTrack
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_apple_audio_toolbox_MusicSequence_MusicSequenceDisposeTrack
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_apple_audio_toolbox_MusicSequence
 * Method:    MusicSequenceGetTrackCount
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_apple_audio_toolbox_MusicSequence_MusicSequenceGetTrackCount
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_apple_audio_toolbox_MusicSequence
 * Method:    MusicSequenceGetIndTrack
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_apple_audio_toolbox_MusicSequence_MusicSequenceGetIndTrack
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_apple_audio_toolbox_MusicSequence
 * Method:    MusicSequenceGetTrackIndex
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_apple_audio_toolbox_MusicSequence_MusicSequenceGetTrackIndex
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_apple_audio_toolbox_MusicSequence
 * Method:    MusicSequenceSetAUGraph
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_apple_audio_toolbox_MusicSequence_MusicSequenceSetAUGraph
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_apple_audio_toolbox_MusicSequence
 * Method:    MusicSequenceGetAUGraph
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_apple_audio_toolbox_MusicSequence_MusicSequenceGetAUGraph
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_apple_audio_toolbox_MusicSequence
 * Method:    MusicSequenceLoadSMF
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_apple_audio_toolbox_MusicSequence_MusicSequenceLoadSMF
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_apple_audio_toolbox_MusicSequence
 * Method:    MusicSequenceSaveSMF
 * Signature: (IIS)I
 */
JNIEXPORT jint JNICALL Java_com_apple_audio_toolbox_MusicSequence_MusicSequenceSaveSMF
  (JNIEnv *, jclass, jint, jint, jshort);

/*
 * Class:     com_apple_audio_toolbox_MusicSequence
 * Method:    MusicSequenceReverse
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_apple_audio_toolbox_MusicSequence_MusicSequenceReverse
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_apple_audio_toolbox_MusicSequence
 * Method:    MusicSequenceSetMIDIEndpoint
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_apple_audio_toolbox_MusicSequence_MusicSequenceSetMIDIEndpoint
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_apple_audio_toolbox_MusicSequence
 * Method:    MusicSequenceGetTempoTrack
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_apple_audio_toolbox_MusicSequence_MusicSequenceGetTempoTrack
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_apple_audio_toolbox_MusicSequence
 * Method:    MusicSequenceGetSecondsForBeats
 * Signature: (IDI)I
 */
JNIEXPORT jint JNICALL Java_com_apple_audio_toolbox_MusicSequence_MusicSequenceGetSecondsForBeats
  (JNIEnv *, jclass, jint, jdouble, jint);

/*
 * Class:     com_apple_audio_toolbox_MusicSequence
 * Method:    MusicSequenceGetBeatsForSeconds
 * Signature: (IDI)I
 */
JNIEXPORT jint JNICALL Java_com_apple_audio_toolbox_MusicSequence_MusicSequenceGetBeatsForSeconds
  (JNIEnv *, jclass, jint, jdouble, jint);

#ifdef __cplusplus
}
#endif
#endif
